In [1]:
import numpy as np
import sys
print('Python version: ' + sys.version[:5])

Python version: 3.8.5


# Learning Numpy

## Basics

In [2]:
# Initialization
a = np.array([1, 2, 3], dtype="int16")
print(a)
a.astype('float32')

[1 2 3]


array([1., 2., 3.], dtype=float32)

In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
print("Dimension of a:", a.ndim)
print("Dimension of b:", b.ndim)

Dimension of a: 1
Dimension of b: 2


In [5]:
# Get Shape
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

Shape of a: (3,)
Shape of b: (2, 3)


In [6]:
# Get DataType and Size
print("Type of a:", a.dtype)
print("Type of b:", b.dtype)
print("Type of a items size(bytes):", a.itemsize)
print("Type of b items size(bytes):", b.itemsize)

Type of a: int16
Type of b: float64
Type of a items size(bytes): 2
Type of b items size(bytes): 8


In [7]:
# Get total size
print("Size of a(bytes):", a.size * a.itemsize)
print("Size of b(bytes):", b.size * b.itemsize)
# a.size * a.itemsize = a.nbytes
print("Size of a(bytes):", a.nbytes)
print("Size of b(bytes):", b.nbytes)

Size of a(bytes): 6
Size of b(bytes): 48
Size of a(bytes): 6
Size of b(bytes): 48


## Accessing  

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [9]:
#Get a specific element [r, c]
a[1, 5]

13

In [10]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [12]:
# Getting a little more fancy [startindex:endindex:step]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [13]:
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

## Initializing Different Types of Arrays

In [14]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# All 1s matrix
np.ones((3, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [16]:
# Any other number
np.full((3, 2, 2), 12, dtype='float32')

array([[[12., 12.],
        [12., 12.]],

       [[12., 12.],
        [12., 12.]],

       [[12., 12.],
        [12., 12.]]], dtype=float32)

In [17]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
a = [1, 2]
print(type(a))
a = np.asarray(a)
print(type(a))
a = [1, 2]
a = np.asanyarray(a)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a, 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
# Random decimal numbers

np.random.rand(4, 2)

array([[0.15950742, 0.14874082],
       [0.86227896, 0.66489497],
       [0.34614132, 0.12628027],
       [0.0836899 , 0.22743309]])

In [22]:
np.random.random_sample(a.shape)

array([[0.60482031, 0.28191951, 0.48286495, 0.96715144, 0.63589478,
        0.23455394, 0.68047526],
       [0.33979163, 0.18916638, 0.10913247, 0.22838819, 0.46986637,
        0.20791404, 0.16071461]])

In [23]:
# Random integer values

np.random.randint(10, size=(4, 3))

array([[9, 4, 9],
       [2, 0, 3],
       [2, 2, 7],
       [1, 6, 1]])

In [24]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Repeat an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
r1 = np.repeat(arr, 3, axis=0)
r2 = np.repeat(arr, 3, axis=1)
print(r1, end="\n\n")
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [26]:
o = np.ones((5, 5))
o[1:4, 1:4] = 0
o[2, 2] = 9
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Math

In [27]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [28]:
a + 2

array([3, 4, 5, 6])

In [29]:
a - 2

array([-1,  0,  1,  2])

In [30]:
a * 2

array([2, 4, 6, 8])

In [31]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [32]:
a // 2

array([0, 1, 1, 2], dtype=int32)

In [33]:
a += 2
a

array([3, 4, 5, 6])

In [34]:
b = np.array([1, 0, 1, 0])
a + b

array([4, 4, 6, 6])

In [35]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [36]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [37]:
## Linear Algebra

In [38]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
a, b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [39]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [40]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [41]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats)

1

In [43]:
np.max(stats)

6

In [44]:
np.min(stats, axis=1)

array([1, 4])

In [45]:
np.sum(stats)

21

## Reorganizing Arrays

In [46]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [48]:
after = before.reshape((2, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
v1 = np.ones((2, 4))
v2 = np.zeros((2, 2))
np.hstack((v1, v2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from file

In [51]:
#np.genfromtxt(filename, delimiter="delimiter")

## Boolean Masking and Advanced Indexing

In [52]:
a = np.array([[int(i) for i in range(10)],[int(j) for j in range(10, 20)]])
print(a)
a > 5

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [53]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
a[[1, 0], [3, 1]]

array([13,  1])

In [55]:
np.any(a > 11, axis = 0)

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
np.all(a > 5, axis = 1)

array([False,  True])

In [57]:
((a > 5) & (a < 12))

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False, False,
        False]])

In [58]:
(~((a > 5) & (a < 12)))

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [59]:
b = np.array([int(i) for i in range(1, 31)])
b = b.reshape((6, 5))
print(b)
print(b[[0, 1, 2, 3],[1, 2, 3,4]])
b[[0, 4, 5], 3:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[ 2  8 14 20]


array([[ 4,  5],
       [24, 25],
       [29, 30]])